### ISSUE TITLE
Delay of initial agent is pretty long [OneDrive listener]

### ISSUE THREAD

**Issue by jammys** [EmpireProject/Empire#1155]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
Kali Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Hello! I encounter a problem with the onedrive listener.

In fact when I get an agent Empire begins by  immediately showing the text "**[*] New agent 5P1X2SD checked in**" in blue, so it's normal. But a delay of more than 5min surges before I can interact with the agent. (I mean before "**[+] Initial agent 5P1X2SD from 0.0.0.0 now active**" appears)

Second tiny problem, when removing agents, onedrive listeners immediately restages it with other name. "**[*] Invalid agent, deleting results/5P1X2SD.txt and restaging**"

I would like to have confirmation of the normality of these behaviors?

**Comment by mr64bit** [comment]
Hi jammys,

What are the values of your PollInterval and DefaultDelay for the Onedrive listener?

The staging process is much longer than a normal HTTP listener because the agent and listener cannot immediately reply to each other, they just have to watch the Onedrive folder for new files. The delay for the agent could be decreased, but would result in more network activity during the staging process.
You could remove the "*2" on lines 122 and 196 of https://github.com/EmpireProject/Empire/blob/master/data/agent/stagers/onedrive.ps1 for example.

I usually run the Onedrive listener with a DefaultDelay of 30, and I get a full agent within 2 minutes of staging.

For your second question: Yes, that's normal. It's not actually restaging the agent right away. (you'd see a "new agent checked in" message for that) It's just putting a small message in the Onedrive folder to let the agent know that it needs to restage. If the agent is actually dead, then nothing else will happen, but if the agent is still running, it will see that message and restart the staging process.

**Comment by jammys** [comment]
Thank you for your prompt response.

I did'nt touch PollInterval and DefaultDelay values (these are default).
I will follow your advice : reduce the DefaultDelay and trying to remove the lines from onedrive.ps1 :)
