### ISSUE TITLE
Two Dollar ($) signs in password cause sudo_spawn/stager to fail

### ISSUE THREAD

**Issue by chumstick** [EmpireProject/Empire#1169]
## Empire Version

2.5

## OS Information (Linux flavor, Python version)

Kali 2018.2

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Expected: After setting the password parameter and selecting the target, a user runs sudo_spawn. After valid results have been returned, the python stager (stage 1) is sent to the target and a new agent running under root results from the completed process.

Error: When using sudo_spawn, if the target password has more than one dollar sign, the spawn fails. No error is given as the process hangs after showing “Valid results returned from [target]”

## Screenshot of error, embedded text output, or Pastebin link to the error

![img_0172](https://user-images.githubusercontent.com/3391773/41637719-4920fce0-7423-11e8-8c59-a885747d3782.jpg)

![img_0173](https://user-images.githubusercontent.com/3391773/41637727-52a238d8-7423-11e8-9406-43baf0d7a692.jpg)

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi,

It's because of this line in the source module https://github.com/EmpireProject/Empire/blob/e37fb2eef8ff8f5a0a689f1589f424906fe13055/lib/modules/python/privesc/multi/sudo_spawn.py#L108

`shell=True` option executes your command in a (ba)sh, so `$` signs are interpreted  

![escape](https://user-images.githubusercontent.com/18633286/41641671-4e25151c-7466-11e8-8962-8803be116843.png)

As a workaround, you can escape `$` with `\`
:sunflower:

**Comment by chumstick** [comment]
D'oh! Of course. I sure spent a lot of time writing up an issue with a pretty obvious workaround. I'm going to blame it on lack of sleep. 

Thanks @ThePirateWhoSmellsOfSunflowers!
