### ISSUE TITLE
Connecting to remote/external/WAN IP issue

### ISSUE THREAD

**Issue by Yadarma** [EmpireProject/Empire#1255]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
Kali linux

##Details
If I need agents to connect to server from public IP, should I use http listener with BindIP or 2 listeners http and http_hop?

Could you provide an exmple like:
set Host ....
set Port ....

BTW, i tried both approaches from previous issues but nothing worked from. Sometimes I saw from command "netstat -lntup" port/connection from the remote agent but NOT detect in Empire!!!
Thanks in advance

**Comment by mr64bit** [comment]
You don't need two listeners (though you could use http_foreign for this)
Host is what the agent will try to connect to. (include protocol and port if it's not the default. http://hostname[.]com:8080)

BindIP and Port are what Empire will listen on. BindIP can usually be left at 0.0.0.0, and set Port to what you want to listen on, if it's different from your public facing port.

For example, if you had port 80 on a public IP forwarded to port 8080 on your Kali box, you'd do the following.
`set Host http://<public ip>` <- can leave off port, since 80 is the default for HTTP
`set BindIP 0.0.0.0` <- or the IP of your Kali box's interface
`set Port 8080`

**Comment by Yadarma** [comment]
About the forwarding rules in the router, they should be my Kali Linux internal ip but what about the port? Must it be 8080.
Btw when I try your solution I will feedback you any issue our success.
Thanks mr64bit

**Comment by mr64bit** [comment]
Port is whatever you want it to be, as long as the forwarded internal port is the same as the Port option in your listener.

**Comment by Yadarma** [comment]
Not working for me.
errors:
![a](https://user-images.githubusercontent.com/34219183/47368919-40587e00-d6eb-11e8-91ee-111efce41dbf.png)
![b](https://user-images.githubusercontent.com/34219183/47368948-4c444000-d6eb-11e8-9352-a84faafb522e.png)
