### ISSUE TITLE
Do nothing when interacted with agent.

### ISSUE THREAD

**Issue by vinnt2** [EmpireProject/Empire#456]
## Empire Version

1.6.0

## OS Information (Linux flavor, Python version)

Kali Linux 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

When interacted with agent do none commands that listed on help .

## Screenshot of error, embedded text output, or Pastebin link to the error

http://prnt.sc/e8fs0n

## Any additional information
Waited for 2 minutes till command executed too ,  but did nothing.

**Comment by vinnt2** [comment]
I saw very related bugs out there : 

https://github.com/EmpireProject/Empire/issues/368

and it says error on epoch But could one of you guys leave some detailed instruction to fix it? :) thanks anyway

**Comment by vinnt2** [comment]
Still no one ? i need help.

**Comment by cobbr** [comment]
Usually when this happens to me it's due to a clock issue on the Kali box. Run `date` and see if the output is what you would expect. The agent won't respond to requests if the date is off. If this is the problem, I usually fix it by running `service ntp restart`.

If this isn't the problem, you should probably try running Empire with debugging enabled: `./empire --debug 2`. This will give you a better clue of what is going on. Share your output from that if you can't figure it out.
