### ISSUE TITLE
--rest tries to start all the listeners

### ISSUE THREAD

**Issue by Viss** [EmpireProject/Empire#507]
## Empire Version
2.0.0-beta, fresh from git as of Friday May 12th, 5pm PST

## OS Information (Linux flavor, Python version)
ubuntu, x64

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

when attempting to start the empire with --rest, empire attempts to actually start all the listeners and bails out with errors saying that the ports are already in use. This is because I've been trying to use the API to expand the functionality of an already-running instance of empire. 

With the previous version of empire, the user was able to start one version of empire (the one the user would use by hand) and a second version of empire with the rest API enabled.

this would allow the user to have a functional version of empire up and running, while also being able to run automated scripts against the API to do things like dramatically expand the autorun capabilities of empire, or conduct specific actions on specific shells if they meet a certain criteria like get/put files, take screenshots, enable keylogging, fetch the keylogs etc. 

It seems the easy fix for this is to simply tell empire to not start the listeners if --rest is passed to it at the commandline, so that the previous functionality can continue to be used.

**Comment by bneg** [comment]
This is related to another issue I need to file a bug about. I haven't done a ton of testing on the problem, but I spent quite a bit of time in the API code a few weekends ago.

Here's more information from what I've been able to find:
When you fire up Empire, it looks in it's SQLite DB, and fires up any listeners that may have been recorded in there (works well for crash recovery). Not only does it fire up listeners, but it keeps the details of those listeners in memory. Or maybe you start a listener manually, and its details get recorded to the DB and added onto the dict in mem.

Next, you go to fire up the REST API and it has no access to the other Empire's memory. But it CAN read from the database, and because it doesn't know if some other empire instance is running or not, it tries to fire up all the listeners that were recorded in the DB. The user sees the error messages of "port in use", but --rest should still work (requiring you to ignore the errors).

Now, this works both ways and we get into the bug that I need to file. If you start a listener from a script via the API, it never shows up in the Empire console app if it was running parallel with --rest. IOW, the console doesn't know about the new listener that was started because it never checks the DB for updates on it's own.

The REST API OTOH, because it always checks the DB for every call should be the authority. So, if you start a listener with --rest or the console, you should be able to query it via the API. 

Finally, if you're using --headless, this problem never appears as you're using the API for everything.

**Comment by byt3bl33d3r** [comment]
I've run into this bug as well while updating CME's empire_exec module. Will see if I can track down the issue.

**Comment by byt3bl33d3r** [comment]
So I've managed to find the problem, basically the ```restAPI``` argument passed from the main empire script [here](https://github.com/EmpireProject/Empire/blob/master/empire#L193) to ```lib/common/empire.py``` [here](https://github.com/EmpireProject/Empire/blob/master/lib/common/empire.py#L63) is ignored, so when you start the REST API it tries to start existing listeners in the database as well. 
Creating a fix for the REST API so it doesn't start listeners in the db on startup is trivial.

Problem is because of how Empire 2.0 now loads the listener modules (each listener is now a thread in a dictionary) if you do start the REST API **after** starting Empire there is no way for it to know about existing listeners so you won't be able to interact with them through the REST API

The lazy solution (and probably the most viable one imho) would be to just have an argument in the main ```empire``` script which starts both the console and the REST API. I have no clue what to call the flag though lol

 @HarmJ0y @xorrior @rvrsh3ll any thoughts?

Cheers

**Comment by hillar** [comment]
--with-rest

**Comment by byt3bl33d3r** [comment]
There really was no use for the existing --rest flag due to the reasons I mentioned above. When the PR is merged the --rest flag will start the API and the console.

Cheers

**Comment by Viss** [comment]
Ah, perfect! :D

**Comment by xorrior** [comment]
Addressed in #529
