### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by johnjohnsp1** [EmpireProject/Empire#539]
## Empire Version
latest (issued git clone on 05/28/2017

## OS Information (Linux flavor, Python version)
Linux 2017 4.9.0-kali4-amd64 #1 SMP Debian 4.9.25-1kali1 (2017-05-04) x86_64 GNU/Linux
Python 2.7.13

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
once git cloned the empire from repo I used those commands:
empire/setup/install.sh
empire/setup/setup_database.sh
empire/setup/cert

## Screenshot of error, embedded text output, or Pastebin link to the error
error:

Traceback (most recent call last):
  File "./empire", line 1294, in <module>
    main = empire.MainMenu(args=args)
  File "/pentest/powershell/empire-ps/lib/common/empire.py", line 75, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist')
TypeError: 'NoneType' object is not iterable

**Comment by xorrior** [comment]
You only need to run install. The install script will run the database setup. Try running reset.shOn May 28, 2017 1:01 PM, johnjohnsp1 <notifications@github.com> wrote:Empire Version
latest (issued git clone on 05/28/2017
OS Information (Linux flavor, Python version)
Linux 2017 4.9.0-kali4-amd64 #1 SMP Debian 4.9.25-1kali1 (2017-05-04) x86_64 GNU/Linux
Python 2.7.13
Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
once git cloned the empire from repo I used those commands:
empire/setup/install.sh
empire/setup/setup_database.sh
empire/setup/cert
Screenshot of error, embedded text output, or Pastebin link to the error
error:
Traceback (most recent call last):
File "./empire", line 1294, in 
main = empire.MainMenu(args=args)
File "/pentest/powershell/empire-ps/lib/common/empire.py", line 75, in init
(self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist')
TypeError: 'NoneType' object is not iterable
Any additional information

**Comment by johnjohnsp1** [comment]
thanks for the reply, did run again ./install and everything went fine is now working !

**Comment by royharoush** [comment]
do you guys know of the correct version to use of the forked empire ?
