### ISSUE TITLE
[feature request] stale agent indicator(s)

### ISSUE THREAD

**Issue by frohoff** [EmpireProject/Empire#570]
It would be useful to provide a way to quickly determine whether an agent is stale or not without having to constantly check and compare the last seen time with the calculated check-in window. Practical uses of this would be knowing when agents might be disappearing due to defender actions (downing processes/hosts or blocking c2 addresses) or when agents have come back online and are ready for further offensive actions. 

This could be as simple as a small indicator character somewhere on the console's `list agents` view (similar to the asterisk for high integrity agents) or more sophisticated such as providing a `stale` boolean flag or `stale_time` timestamp field in the REST API's list agents response that could be used to more easily implement out-of-band stale/unstale agent notifications.

I'd be happy to submit a PR if this is deemed a useful feature.

**Comment by xorrior** [comment]
Sure, PR's are always welcome.On Jun 8, 2017 6:22 PM, Chris Frohoff <notifications@github.com> wrote:It would be useful to provide a way to quickly determine whether an agent is stale or not without having to constantly check and compare the last seen time with the calculated check-in window. Practical uses of this would be knowing when agents might be disappearing due to defender actions (downing processes/hosts or blocking c2 addresses) or when agents have come back online and are ready for further offensive actions.
This could be a simple as a small indicator character somewhere on the console's list agents view (similar to the asterisk for high integrity agents) or more sophisticated such as providing a stale boolean flag or stale_time timestamp field in the REST API's list agents response that could be used to more easily implement out-of-band stale/unstale agent notifications.
I'd be happy to submit a PR if this is deemed a useful feature.

**Comment by mr64bit** [comment]
There's an undocumented argument for the `list` command when in the agents
list. If you type `list 5`, it will show only agents that have checked in
with the past 5 minutes. Alternatively, `list stale` will list stale agents.

The code for filtering which agents to display is at
https://github.com/EmpireProject/Empire/blob/master/lib/common/empire.py#L625

and for formatting the agent list to print
https://github.com/EmpireProject/Empire/blob/master/lib/common/messages.py#L169

Shouldn't be to hard to add in what you're looking for. :)
