### ISSUE TITLE
[feature request] option to include module parameters in agent logs

### ISSUE THREAD

**Issue by frohoff** [EmpireProject/Empire#571]
The existing Empire agent logs have been an invaluable time-saver in keeping records during operations. One area for improvement would be to allow a user-configurable option (cli or global ) to include module parameters in agent log output when modules are executed instead of the current terse single-line output:

```
2017-05-18 09:24:41 : 
Tasked agent to run module lateral_movement/invoke_wmi
```

Some modules could have fairly verbose and/or numerous options, so it might make sense to only log options that differ from their default value and perhaps concatenate them all onto a single line with separator characters:

```
2017-05-18 09:24:41 : 
Tasked agent to run module lateral_movement/invoke_wmi
Options: Listener='http://myc2.net', UserName='User1', ComputerName='WIN1', Password='Terrible'
```

I'd be happy to submit a PR if this is deemed a useful feature.

**Comment by xorrior** [comment]
Sure, PR's are always welcome.On Jun 8, 2017 6:47 PM, Chris Frohoff <notifications@github.com> wrote:The existing Empire agent logs have been an invaluable time-saver in keeping records during operations. One area for improvement would be to allow a user-configurable option (cli or global ) to include module parameters in agent log output when modules are executed instead of the current terse single-line output:
2017-05-18 09:24:41 : 
Tasked agent to run module lateral_movement/invoke_wmi

Some modules could have fairly verbose and/or numerous options, so it might make sense to only log options that differ from their default value and perhaps concatenate them all onto a single line with separator characters:
2017-05-18 09:24:41 : 
Tasked agent to run module lateral_movement/invoke_wmi
Options: Listener='http://myc2.net', UserName='User1', ComputerName='WIN1', Password='Terrible'

I'd be happy to submit a PR if this is deemed a useful feature.
