### ISSUE TITLE
Empire is not spawning result on current menu

### ISSUE THREAD

**Issue by ChaitanyaHaritash** [EmpireProject/Empire#584]
## Empire Version

2.0

## OS Information (Linux flavor, Python version)
Attacker :
         Kali Rolling(Mate)
         python 2.7

Victim Box :
        Windows 7
        Powershell V2.0
## Issue
I simply wrote a post module which will perform some scans on victim box.. so i expected module to give me result on same menu when i execute it but  at the same time when i interacts with agent, it immediately spawns the result which i think strange and i don't know why, when i executed same module again.. it didn't worked even when i interacted with agent again. Tho i didn't found old modules behaving same.

## ScreenShots 
![bug](https://user-images.githubusercontent.com/16261173/27456192-bfbdb27c-57bd-11e7-8b0c-2f49495fa956.PNG)

## Any additional information
N/A

**Comment by xorrior** [comment]
@ChaitanyaHaritash So I'm not sure what the issue is exactly. It could be many things. It could be that there is a flaw somewhere in your code that is causing the inconsistent behavior. In the module code, the IsBackground flag will determine how the output of your module is handled. I would need some more information such as output from running empire with the --debug 2 flag and also some code.

**Comment by ChaitanyaHaritash** [comment]
actually its HostRecon.ps1 by @dafthack (https://github.com/dafthack/HostRecon), even i think so cos later after this module i made couple of modules and i didn't noticed this issue.. still ill give you referral link to my code if you finds anything odd then you can point it out else we can leave it here :) 
code : https://github.com/ChaitanyaHaritash/My-Exploits/tree/master/Emipre%20-stagers%20-%20modules/HostRecon
