### ISSUE TITLE
Internal pivot (listener)

### ISSUE THREAD

**Issue by tbolt678** [EmpireProject/Empire#601]
## Empire Version
2.0

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

The management redirector module has been moved to inactive, but the documentation still reference this module as the way to setup a internal pivot.

Is redirector still the preferred internal pivot to listener method or is there a other module?

**Comment by PoSHMagiC0de** [comment]
I, too, am wondering about this.  I remember it being in 1.6 so I installed 2.0 on my Raspberry Pi W Zero, got it all working so I could use P4wnP1 project's hid_backdoor to create an agent and control it via wireless nearby.  Because of the method the pi connects via USB ethernet, it is like it is on another subnet so the cleanly route traffic for empire I was going to have it setup a redirector.  Welp,  i was shocked when I got done and was ready to try the redirector just to find it missing in 2.0 hehe.  Looks like I will have to pull 1.6 to accomplish this for now.

**Comment by elitest** [comment]
I never used the redirector.  Isn't this handled by the socks management module now?  Can this be closed?

**Comment by PoSHMagiC0de** [comment]
I looked up the socks management module.  It is available only for python.
There isn't one for Powershell.

**Comment by elitest** [comment]
Ah gotcha!

**Comment by manasmbellani** [comment]
Hi, 
Any plans to reintroduce management/redirector pivot listener in powershell empire soon?

**Comment by xorrior** [comment]
Done dad46533dae0b3d498150cd1c139c595dcac2873
