### ISSUE TITLE
"shell set" crashes agent

### ISSUE THREAD

**Issue by binary1985** [EmpireProject/Empire#713]
## Empire Version
2.1

## OS Information (Linux flavor, Python version)
Kali2017.1 64 Bit

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Expected: See currently set environmental variables when executing "shell set"

## Screenshot of error, embedded text output, or Pastebin link to the error
https://pastebin.com/cJ4j59ZH

**Comment by 0x1c** [comment]
Confirmed bug on Windows 7 target.

```2017-10-06 05:23:25 Agents : [*] Tasked TDM3SGXE to run TASK_SHELL
2017-10-06 05:23:27 Agents : [*] handle_agent_data(): sessionID TDM3SGXE issued a TASKING_REQUEST
2017-10-06 05:23:27 listeners/http : [*] Agent from X.X.X.X retrieved taskings```

Then the agent dies.
I couldn't get to the bottom of this but I do have a workaround, use "shell cmd /c set"

**Comment by binary1985** [comment]
Hey sorry I didn't do more work into this one. "set" in powershell operates differently than set in cmd. How hard would it be for you to just write an alias for set to do "Get-ChildItem Env:"(powershell version of set)

**Comment by xorrior** [comment]
@binary1985 We won't be added an alias in empire for SET as there is already an alias built into Powershell and would lead to unnecessary confusion. "shell gci Env:" works just fine. Thanks

**Comment by binary1985** [comment]
It doesn't resolve the bug though does it? The alias was a request to make the set function work which I dont really care about and 0x1c already provided a workable solution, this github issue is a request to fix the bug of my shells dying by typing shell set.

**Comment by xorrior** [comment]
@binary1985 You're agents are dying because when you type set in a powershell prompt, this is the result. 
![image](https://user-images.githubusercontent.com/9156069/31346449-1dbae22c-ace7-11e7-9a90-d03b2226793a.png)

The agent is not dead but halted, waiting for input from stdin. Now we could alias set => gci Env:. The only issue with that is when an operator actually wants to use the SET alias in powershell, it will no longer have the desired result. Since this is already a mapped alias in powershell, I have reservations about making this change. Using "shell gci Env:" is a sufficient solution IMO.
