### ISSUE TITLE
[!] strip_python_comments is deprecated and should not be used

### ISSUE THREAD

**Issue by DigApis-Michael** [EmpireProject/Empire#911]
## Empire Version
2.4
Installed today on Debian 7, 2.6 kernel.

## OS Information (Linux flavor, Python version)
python 2.7.3

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
 - listener: http, using http://xx.xx.xx.xx:80
 - launcher: launcher python http

## Screenshot of error, embedded text output, or Pastebin link to the error
 I got agent initial messages first, then the following warning:

>  [!] strip_python_comments is deprecated and should not be used

 After that, agents looks like dead. Just not responding to any command.

 Tested target is Kali 2 rolling, x64 version.

## Any additional information
I'm not using the docker version, just ./setup/install.sh, no problems prompted.

Any idea what is going on?

Thank you!

**Comment by DakotaNelson** [comment]
I don't believe the message has any impact on the agent.

(You can skip this next paragraph, it's the "why" of that message but doesn't help you solve the agent problem.)

Here's the short of it: `strip_python_comments` is a function that, well... strips the python comments out of the agent. In the new version, instead of a custom-written function, Empire uses [pyminifier](https://liftoff.github.io/pyminifier/). The old function now prints a message to nag me (or someone... but probably me 😄 ) into replacing all of the remaining places that function is called with the new, improved version, and to make sure the old function doesn't get included in any new code (for example, if someone has a third-party addon to Empire that uses the function, I don't want it to just disappear on them, so this is a warning period).

SO. I don't think that message should cause trouble - the function is exactly the same as it was in the previous version - but that doesn't exactly help figure out what the problem actually is.

**Comment by xorrior** [comment]
Hmmm it may have something to do with the logic to check the default response in the agent. I'll take a look when i can.

**Comment by xorrior** [comment]
@DigApis-Michael Did you reset the db after the upgrade? The reason I ask is because if the db was reset and the agents were removed, when they call back, the server will return a 401 response. On the powershell side this will cause the agent to call the Start-Negotiate function and re-stage. Unfortunately on the python side I tried several methods to call the function responsible for staging but just couldn't get it jiggling. For some reason the exec function doesn't work well when trying to use a function as a global. So currently, the python agents will just exit instead of constantly making request to the server. @DakotaNelson would you have any idea of how to call a function from within an exec code block? 

Alternatively, this could be something with the agent exiting when the server returns a 404 response. However, I patched this out yesterday so the server should return a 200 response as long as the routing packet is present (session cookie).

**Comment by DigApis-Michael** [comment]
hey, guys,

I `reset.sh` ed, and also in the directory, I did `git pull` to keep empire updated.

Http listeners set up, and laucher python,

Paste to the kali, hit enter.

Got the agent initial message, with the depreceted message as described.

Interact with the agent, no responding.


On kali,
`ps aux | grep 1317` which is the process id, not found.....

What's the problems guys?
The account I ran the launcher on kali is `root`, this can't be the reason.

**Comment by DigApis-Michael** [comment]
I also `git clone -b dev http://[empire]` and did the same setup steps,

Still no responding.

**Comment by DigApis-Michael** [comment]
Additionally, I did this to a windows target `win 7 x64`,

Seems responding....
`shell id`, responding well
`shell dir`, not responding...
`usemodule [get_localgroup]`, job started, but no info comes back.

I also did `sleep 0`, which give me a message saying done.

I'm feeling at sea right now.

**Comment by xorrior** [comment]
@DigApis-Michael I'm not sure what's going on. 

1. You tasked a Windows host with "shell id" and it returned results?
2. Can you provide some output from running empire with the --debug 2 flag after running some commands? 
3. There seems to be an issues with all of the powerview modules (#909). So I'll take a look at that. 

Also, I can't reproduce any of the behavior that you are experience with your agents. I tested both a python agent (debian) and powershell (Win 10). Both agents responded to commands and returned output without issue. Once you provide the output for ? 2, we'll be able to troubleshoot.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hello,
I manage to reproduce the bug : 
Empire version : Github's version (git clone, master branch)
Empire server : Ubuntu 16.04
Victim : osx 10.12.6 (python launcher)

However, the agents works fine and `shell id`, usemodule are ok. The error seems to be only a "warning" and does not impact the communication.

**Comment by xorrior** [comment]
@ThePirateWhoSmellsOfSunflowers The warning message isn't necessarily an error. It's from the python jinja module and doesn't effect anything. I just can't reproduce the issue where agents stop communicating. I feel like there are other factors in play here.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Ok, my bad, I misunderstood the point

**Comment by DakotaNelson** [comment]
Just to clear up the warning message about `strip_python_comments`, here's the relevant code:

https://github.com/EmpireProject/Empire/blob/5c3edbbdfffcb501142d9195514e7f31216616f5/lib/common/helpers.py#L169-L179

And here's the history of that code:

https://github.com/EmpireProject/Empire/blame/5c3edbbdfffcb501142d9195514e7f31216616f5/lib/common/helpers.py#L169-L179

The actual logic of it has been the same for over a year, the only recent changes are a print statement and a comment.

Hopefully that clears up some confusion around the warning - it's definitely on me for not removing all of the uses of that function right away.

**Comment by xorrior** [comment]
@DigApis-Michael feel free to re-open this once you can provide some additional information.
