### ISSUE TITLE
Question: Reconnect agent after IP block

### ISSUE THREAD

**Issue by CryptomaticSquirrel** [EmpireProject/Empire#912]
## Any additional information

Hello. I was just wondering what is the preferred method to get an agent to connect back after the initial IP/hostname has been blocked.
Can I submit a list of IP's or hostnames or is there a way for the agent to execute commands if it cannot reach back anymore?

**Comment by DakotaNelson** [comment]
I've been thinking about this a lot, especially in light of [this DailyDave post](http://lists.immunityinc.com/pipermail/dailydave/2017-November/001436.html).

I think the simple answer is what you said - a list of C2 methods, where the agent tries the first, falls back to the second if it doesn't work, and so on.

There's some more exotic stuff I think might be interesting - setting up an agent-to-agent comms interface (with their own C2 methods for flexibility) the same way agent-to-home C2 works, and keeping agents appraised of each other in order to let them dynamically (or on command) link to each other based on available backhaul C2 methods. This could somewhat resemble the [SMB beacon](https://www.cobaltstrike.com/help-smb-beacon) in Cobalt Strike and allow for internal comms between agents.

Agent automation would also be awesome - I think it'd be really interesting to have a set of pre-defined 'events' that can occur to an agent, and the possibility to register a handler (or several) for each of the events. Agent loses a connection for too long? The default handler is to kill it, but you can register a custom handler (or use one from a library of handlers) to instead try a backup C2 method, or maybe even write its state to disk for later pickup... or whatever. Agent notices that a new local admin has logged onto the machine? Automatically try to grab their cred material and send it back home... or again, whatever. It would be an interesting challenge to write a modular system that allows people to add new events and new handlers for whatever sort of automation they'd like to see. This could eventually get to the point where certain agents don't need interaction from an operator to carry out very specific targeted missions - essentially "one shot" automated agents.

Of course, that stuff is A) hard and B) more likely to fail. I really like the idea of being able to configure multiple C2 methods/configuration packages and falling back from one to the other.

**Comment by xorrior** [comment]
@DakotaNelson hehe SMB comms is one of several things I want to tackle this year....

**Comment by CryptomaticSquirrel** [comment]
Thanks a lot for the input !
As I understand I will probably have to find a way to make this work on my own. I will come back to this and see about a solution a little later. When it has become more of a priority.
