### ISSUE TITLE
Module trollsploit/wallpaper: "error running command: Cannot add type. Compilation errors occurred."

### ISSUE THREAD

**Issue by meldridge** [EmpireProject/Empire#934]
## Empire Version
2.4

## OS Information (Linux flavor, Python version)
Kali rolling, Python 2.7.14+

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
On a powershell agent, Windows 10 (medium integrity process): usemodule trollsploit/wallpaper
Set LocalImagePath to jpg file
execute

## Screenshot of error, embedded text output, or Pastebin link to the error
(Empire: powershell/trollsploit/wallpaper) > run
[>] Module is not opsec safe, run? [y/N] y
(Empire: powershell/trollsploit/wallpaper) > 
error running command: Cannot add type. Compilation errors occurred.

## Any additional information
Have previously used this same module/image combination on Windows 10 without issue.

**Comment by xorrior** [comment]
@AkenSec we'll look into this.

**Comment by xorrior** [comment]
@meldridge I tested on a recent windows 10 build and the wallpaper changed without issue. I think this may be an isolated issue. Most likely this was due to a missing dependency, but there is no way to know for sure without out the error given by Add-Type. Please let me know if you find that Add-Type fails more consistently with this module. Sorry for the late response.
