### ISSUE TITLE
Proxy settings broken for multi/launcher stager in Empire 2.4

### ISSUE THREAD

**Issue by Strazzom** [EmpireProject/Empire#963]
## Empire Version
2.4

## OS Information (Linux flavor, Python version)
Kali Rolling, python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Expected behavior: `set Proxy 127.0.0.1` under the multi/launcher stager, followed by `execute` should complete successfully.
Actual Behavior: upon `execute` being run, the following error is shown:
`[!] Exception: 'str' object has no attribute 'Split'`

## Screenshot of error, embedded text output, or Pastebin link to the error
https://gist.github.com/Strazzom/f4ba8f3733bffd3bcf3d19921074fa04

## Any additional information
This error only occurs when setting the proxy for the stager. I have tested this with multi/launcher, although it may also be an issue with other stagers. This error does not occur when setting proxy options for the listener.

## Questions about proxy feature documentation
As an aside, the proxy settings are poorly documented. What exactly do the proxy settings do? Is the listener proxy setting the one used by the agent when it connects back? Is the stager proxy setting used for the initial request, or for all subsequent connections from the agent it creates?

In general, where is development in terms of proxy support? I have been looking at the documentation, but according to http://www.powershellempire.com/?page_id=104 it seems that it hasn't been properly implemented.

From the official site:
"For UserAgent and proxy options, default uses the system defaults, none clears that option from being used in the stager, and anything else is assumed to be a custom setting (note, this last bit isn’t properly implemented for proxy settings yet)."

What does custom mean? There is no explanation about the syntax of "custom" either.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
About your questions:
The empire's website is deprecated (last time updated is for the version 1.5) and I think is now unmaintained (and yes, imo the whole empire's project is poorly documented, but I don't blame the maintainers, documenting is hard and boring).

I recently play with proxy and empire, so as far as I understand it, proxy is used for all the requests between the victim and the server (staging, polling task, returning result...). Most of the time, it is the proxy within the victim's company and used to reach the Internet. Options are:

- `none`: via direct connection, using the default route (aka you are certain your victim can access your C&C without proxy)
- `default`:  via the proxy set for the current user context (aka your victim use a proxy, or not, you don't know, let's the OS choose for you)
- 10.0.0.1:8080: (the `custom` option) via a custom proxy, useful, for example, for an agent running under a local account because usually local accounts (such as builtin Administrator) are not set to use a proxy. Thus, `custom` is not a valid option, you have to specy the custom IP:PORT proxy. You can also specify credentials for this custom proxy in the `ProxyCreds` option (`[domain]\user:password`).
Don't know if it help.
🌻

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
About your questions:
The empire's website is deprecated (last time updated is for the version 1.5) and I think is now unmaintained (and yes, imo the whole empire's project is poorly documented, but I don't blame the maintainers, documenting is hard and boring).

I recently play with proxy and empire, so as far as I understand it, proxy is used for all the requests between the victim and the server (staging, polling task, returning result...). Most of the time, it is the proxy within the victim's company and used to reach the Internet. Options are:

- `none`: via direct connection, using the default route (aka you are certain your victim can access your C&C without proxy)
- `default`:  via the proxy set for the current user context (aka your victim use a proxy, or not, you don't know, let's the OS choose for you)
- 10.0.0.1:8080: (the `custom` option) via a custom proxy, useful, for example, for an agent running under a local account because usually local accounts (such as builtin Administrator) are not set to use a proxy. Thus, `custom` is not a valid option, you have to specy the custom IP:PORT proxy. You can also specify credentials for this custom proxy in the `ProxyCreds` option (`[domain]\user:password`).
Don't know if it help.
🌻

**Comment by xorrior** [comment]
@Strazzom Are you inquiring about a socks proxy server within empire? Or a setting the proxy in the listener settings for the agent to use client side?

**Comment by Strazzom** [comment]
The latter. What kind of proxies can I set in the listener, that the agent will use?

**Comment by Strazzom** [comment]
I mean an external proxy, like Tor or another socks proxy. I do not mean one built in to Empire.

**Comment by xorrior** [comment]
Ah,  @Strazzom the agent supports HTTP/s proxies.

**Comment by Strazzom** [comment]
Ok. Thank you for that explanation. Is there any support planned for socks4/5 proxies?

Also unrelated: how might one get on the Slack? I have a lot of things to discuss that might not be ideal for github issues.

**Comment by xorrior** [comment]
@Strazzom Possibly, haven't had much time to think about new features unfortunately. 
For slack: https://adaptiveempire.slack.com/join/shared_invite/enQtMjk4NTUwNzM1NzMwLTYwOTIyZjk3ZjIxOGJiZDM1Y2ZhM2E1NTI5Mjg3MzcwODI5ZTI3YjkxZGE2YWQ0MjIwY2ZkMWMxMTc1ZWRlMjg%C2%A0%E2%80%A6

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
I have the same issue with the war stager, do you manage to fix the error @Strazzom ?

![error](https://user-images.githubusercontent.com/18633286/35966963-b4106bb0-0cbf-11e8-847d-f2709a72c13e.png)

**Comment by xorrior** [comment]
@ThePirateWhoSmellsOfSunflowers after the latest pull I can't seem to replicate that issue. I would look in lib/common/empire.py and lib/common/stagers.py to see the offending 'Split'. Just needs to be lowercase.
